---
- hosts: airavata
  remote_user: ubuntu
  roles:
  - airavata_cleanup

- hosts: zookeeper
  remote_user: ubuntu
  tasks:
  - name: Restart ZooKeeper
    environment:
      JAVA_HOME: "{{java_default}}"
    sudo: yes
    sudo_user: airavata
    command: "{{zookeeper_home}}/bin/zkServer.sh restart"

- hosts: apiserver
  remote_user: ubuntu
  vars:
    airavata_server: api-server
  roles:
  - apiserver

- hosts: orchestrator
  remote_user: ubuntu
  vars:
    airavata_server: orchestrator-server
  roles:
  - orchestrator

- hosts: gfac
  remote_user: ubuntu
  vars:
    airavata_server: gfac-server
  roles:
  - gfac
