---
- hosts: apiserver
  remote_user: "{{user_name}}"
  roles:
  - airavata_cleanup

- hosts: apiserver
  remote_user: "{{user_name}}"
  roles:
  - common

- hosts: zookeeper
  remote_user: "{{user_name}}"
  roles:
   - zookeeper

- hosts: rabbitmq
  remote_user: "{{user_name}}"
  roles:
   - rabbitmq

- hosts: apiserver
  remote_user: "{{user_name}}"
  roles:
   - db

- hosts: apiserver
  remote_user: "{{user_name}}"
  vars:
    airavata_server: airavata-server
  roles:
  - airavata_common

- hosts: zookeeper
  remote_user: "{{user_name}}"
  tasks:
  - name: Restart ZooKeeper
    environment:
      JAVA_HOME: "{{java_default}}"
    sudo: yes
    sudo_user: "{{user_name}}"
    command: "{{zookeeper_home}}/bin/zkServer.sh restart"

- hosts: apiserver
  remote_user: "{{user_name}}"
  vars:
    airavata_server: airavata-server
  roles:
  - airavata_all_in_one
