---
- hosts: all
  remote_user: ubuntu
  roles:
  - common

- hosts: dbserver
  remote_user: ubuntu
  roles:
  - db

- hosts: zookeeper
  remote_user: ubuntu
  roles:
  - zookeeper

- hosts: rabbitmq
  remote_user: ubuntu
  roles:
  - rabbitmq

- hosts: apiserver
  remote_user: ubuntu
  vars:
    airavata_server: api-server
  roles:
  - apiserver

- hosts: orchestrator
  remote_user: ubuntu
  vars:
    airavata_server: orchestrator-server
  roles:
  - orchestrator

- hosts: gfac
  remote_user: ubuntu
  vars:
    airavata_server: gfac-server
  roles:
  - gfac
