---
- name: Install MySql package Red Hat
  yum: name={{item}} state=latest
  with_items:
    - mysql-server
    - MySQL-python
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- name: Install MySql package Ubuntu
  apt: name={{item}} state=latest
    with_items:
      - mysql-server
      - MySQL-python
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


- name: Start MySQL Service
  service: name=mysqld state=started

- name: Create Application Database
  mysql_db: name={{item}} state=present
  with_items:
    - "{{airavata_db}}"
    - "{{appcatalog_db}}"

- name: Create Application DB User
  mysql_user: name={{dbuser}} password={{dbpassword}} priv={{item}}.*:ALL host='%' state=present append_privs=yes
  with_items:
    - "{{airavata_db}}"
    - "{{appcatalog_db}}"

- name: Set up DB firewall rule
  lineinfile: dest={{iptable_rule_file}} state=present 
              regexp="^-A INPUT -s {{hostvars[item]['ansible_default_ipv4']['address']}} -p tcp -m state --state NEW -m tcp --dport {{mysql_port}} -j ACCEPT$"
              line="-A INPUT -s {{hostvars[item]['ansible_default_ipv4']['address']}} -p tcp -m state --state NEW -m tcp --dport {{mysql_port}} -j ACCEPT"
              insertbefore="^-A INPUT -j REJECT .*$"
  with_items: 
    - "{{groups['airavata']}}"
  notify: restart iptables
