---
- name: Configure GFAC server
  template: src=gfac-config.xml dest="{{gfac_server_config}}" owner=ubuntu group=sudo mode=0644

- name: Update GFAC server config file
  replace: dest="{{gfac_server_config}}" regexp="{{item.regexp}}"
           replace="{{item.replace}}"
  with_items:
    - {regexp: "AIRAVATA_HOME", replace: "{{airavata_home}}"}
    - {regexp: "PGA_SERVER", replace: "{{pga_server}}"}
    - {regexp: "PGA_PASSPHRASE", replace: "{{pga_passphrase}}"}
    - {regexp: "PGA_OUTPUTPATH", replace: "{{pga_output_path}}"}

#- name: Set up API Server firewall rule
#  lineinfile: dest={{iptable_rule_file}} state=present
#              regexp="^-A INPUT -p tcp -m state --state NEW -m tcp --dport {{api_server_port}} -j ACCEPT$"
#              line="-A INPUT -p tcp -m state --state NEW -m tcp --dport {{api_server_port}} -j ACCEPT"
#              insertbefore="^-A INPUT -j REJECT .*$"
#  notify:
#    - restart iptables

- name: Start Airavata Server 
  environment:
    JAVA_HOME: "{{java_default}}"
  sudo: yes
  sudo_user: ubuntu
  command: "{{airavata_server_home}}/bin/airavata-server.sh start"
